/// Flutter icons Roomie
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Roomie
///      fonts:
///       - asset: fonts/Roomie.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Roomie {
  Roomie._();

  static const _kFontFam = 'Roomie';

  static const IconData mobilepay = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData visa = IconData(0xf1f0, fontFamily: _kFontFam);
}
